name: "Sample Workflow"
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'You'
      home:
        description: 'location'
        required: false
        default: 'The Universe'

jobs:
  job:
    name: "Job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Hello
        shell: pwsh
        env:
          INPUT_NAME: ${{ github.event.inputs.name }}
          INPUT_HOME: ${{ github.event.inputs.home }}
        run: |
          echo "Hello $env:INPUT_NAME!"
          echo "- in $env:INPUT_HOME!"
